const bingoStems = {
  'tisane' : {
    a : ['entasia', 'taenias'],
    b : ['banties', 'basinet'],
    c : ['acetins', 'cineast'],
    d : ['destain', 'detains', 'instead', 'nidates', 
        'sainted', 'satined', 'stained'],
    e : ['etesian'],
    f : ['fainest'],
    g : ['easting', 'eatings', 'genista', 'ingates', 
        'ingesta', 'seating', 'tagines', 'teasing'],
    h : ['sheitan', 'sthenia'],
    i : ['isatine'],
    j : ['tajines'],
    k : ['intakes'],
    l : ['elastin', 'entails', 'nailset', 'salient',
        'saltine', 'slainte', 'tenails'],
    m : ['etamins', 'inmates', 'tameins'],
    n : ['inanest', 'stanine'],
    o : ['atonies'],
    p : ['panties', 'patines', 'sapient', 'spinate'],
    q : [],
    r : ['anestri', 'antsier', 'nastier', 'ratines', 
        'retains', 'retinas', 'retsina', 'stainer', 
        'stearin'],
    s : ['entasis', 'nasties', 'seitans', 'sestina',
        'tansies', 'tisanes'],
    t : ['instate', 'satinet'],
    u : ['aunties', 'sinuate'],
    v : ['naivest', 'natives', 'vainest'],
    w : ['tawnies', 'waniest'],
    x : ['antisex', 'sextain'],
    y : [],
    z : ['zaniest', 'zeatins']
  },
  'satire' : {
    a : ['aristae', 'asteria', 'atresia'],
    b : ['baiters', 'barites', 'rebaits', 'terbias'],
    c : ['atresic', 'cristae', 'raciest', 'stearic'],
    d : ['aridest', 'astride', 'diaster', 'disrate', 
        'staider', 'tardies', 'tirades'],
    e : ['aeriest', 'seriate'],
    f : ['fairest'],
    g : ['aigrets', 'gaiters', 'seagirt', 'stagier', 
        'triages'],
    h : ['hastier'],
    i : ['airiest'],
    j : [],
    k : [],
    l : ['realist', 'retails', 'saltier', 'saltire',
        'slatier', 'tailers'],
    m : ['imarets', 'maestri', 'misrate', 'smartie'],
    n : ['anestri', 'antsier', 'nastier', 'ratines', 
        'retains', 'retinas', 'retsina', 'stainer', 
        'stearin'],
    o : [],
    p : ['parties', 'pastier', 'piaster', 'piastre',
        'pirates', 'praties', 'traipse'],
    q : [],
    r : ['artsier', 'tarries', 'tarsier'],  
    s : ['artsies', 'satires'],
    t : ['artiest', 'artiste', 'attires', 'iratest', 
        'ratites', 'striate', 'tastier'],
    u : [],
    v : ['raviest', 'vastier', 'veritas'],
    w : ['waister', 'waiters', 'wariest', 'wastrie'],
    x : [],
    y : [],
    z : []
  },
  'retina' : {
    a : [],
    b : [],
    c : ['ceratin', 'certain', 'creatin', 'tacrine'],
    d : ['antired', 'detrain', 'trained'],
    e : ['arenite', 'retinae', 'trainee'],
    f : ['fainter'],
    g : ['granite', 'gratine', 'ingrate', 'tangier',
        'tearing'],
    h : ['hairnet', 'inearth', 'therian'],
    i : ['inertia'],
    j : [],
    k : ['keratin'],
    l : ['latrine', 'ratline', 'reliant', 'retinal', 
        'trenail'],
    m : ['minaret', 'raiment'],
    n : ['entrain', 'trannie'],
    o : [],
    p : ['painter', 'pertain', 'repaint'], 
    q : [],
    r : ['retrain', 'terrain', 'trainer'],
    s : ['anestri', 'antsier', 'nastier', 'ratines', 
        'retains', 'retinas', 'retsina', 'stainer', 
        'stearin'],
    t : ['intreat', 'iterant', 'nattier', 'nitrate',
        'tertian'],
    u : ['ruinate', 'taurine', 'uranite', 'urinate'],
    v : [],
    w : ['tawnier', 'tinware'],
    x : [],
    y : [],
    z : []
  },
  'stearn' : {
    a : ['santera'],
    b : ['banters'],
    c : ['canters', 'carnets', 'nectars', 'recants',
        'scanter', 'tanrecs', 'trances'],
    d : ['darnest', 'stander'],
    e : ['earnest', 'eastern', 'nearest', 'sterane'],
    f : [],
    g : ['argents', 'garnets', 'strange'],
    h : ['anthers', 'thenars'],
    i : ['anestri', 'antsier', 'nastier', 'ratines', 
        'retains', 'retinas', 'retsina', 'stainer', 
        'stearin'],
    j : [],
    k : ['rankest', 'tankers'],
    l : ['antlers', 'rentals', 'saltern', 'sternal'],
    m : ['martens', 'sarment', 'smarten'],
    n : ['tanners'],
    o : ['atoners', 'santero', 'senator', 'treason'],
    p : ['arpents', 'entraps', 'parents', 'pastern',
        'trepans'],
    q : [],
    r : ['errants', 'ranters'],
    s : ['sarsnet'],
    t : ['natters', 'rattens'],
    u : ['natures', 'saunter'],
    v : ['servant', 'taverns', 'versant'],
    w : ['wanters'],
    x : [],
    y : [],
    z : []
  },
  'slater' : {
    a : [],
    b : ['blaster', 'labrets', 'stabler'],
    c : ['cartels', 'clarets', 'crestal', 'scarlet'],
    d : ['dartles'],
    e : ['elaters', 'realest', 'relates', 'reslate', 
        'stealer'],
    f : ['falters'],
    g : ['largest'],
    h : ['halters', 'harslet', 'lathers', 'slather',
        'thalers'],
    i : ['realist', 'retails', 'saltier', 'saltire',
        'slatier', 'tailers'],
    j : [],
    k : ['stalker', 'talkers'],
    l : ['stellar'],
    m : ['armlets', 'lamster', 'tramels'],
    n : ['antlers', 'rentals', 'saltern', 'sternal'],
    o : ['olestra'],
    p : ['palters', 'persalt', 'plaster', 'platers',
        'psalter', 'stapler'],
    q : [],
    r : [],
    s : ['artless', 'lasters', 'salters', 'slaters'],
    t : ['latters', 'rattles', 'starlet', 'startle'],
    u : ['estrual', 'saluter'],
    v : ['travels', 'varlets', 'vestral'],
    w : ['warstle', 'wastrel', 'wrastle'],
    x : [],
    y : ['saltery'],
    z : []
  },
  'regain' : {
    a : ['anergia'],
    b : ['bearing'],
    c : ['anergic'],
    d : ['deraign', 'gradine', 'grained', 'reading'],
    e : ['reginae'],
    f : ['fearing'],
    g : ['gearing', 'naggier'],
    h : ['hearing'],
    i : [],
    j : [],
    k : [],
    l : ['aligner', 'engrail', 'nargile', 'realign',
        'reginal'],
    m : ['germina', 'mangier', 'reaming'],
    n : ['aginner', 'earning', 'engrain', 'grannie', 
        'nearing'],
    o : [],
    p : ['reaping'],
    q : [],
    r : ['angrier', 'earring', 'grainer', 'rangier', 'rearing'],
    s : ['earings', 'erasing', 'gainers', 'reagins', 'regains',
        'reginas', 'searing', 'seringa'],
    t : ['granite', 'gratine', 'ingrate', 'tangier',
        'tearing'],
    u : [],
    v : ['reaving', 'vinegar'],
    w : ['wearing'],
    x : [],
    y : [],
    z : ['zingare']
  }
};

export default bingoStems;
