const shortJQXZs = {
  'j' : [
    'jo',
    'aji', 'haj', 'jab', 'jag', 'jam', 'jar', 'jaw', 'jay', 
    'jee', 'jet', 'jeu', 'jib', 'jig', 'jin', 'job', 'joe', 
    'jog', 'jot', 'jow', 'joy', 'jug', 'jun', 'jus', 'jut', 
    'raj', 'taj', 
    'ajar', 'ajee', 'ajis', 'djin', 'dojo', 'fuji', 'goji',
    'hadj', 'hajj', 'jabs', 'jack', 'jade', 'jagg', 'jags',
    'jail', 'jake', 'jamb', 'jams', 'jane', 'jape', 'jarl',
    'jars', 'jato', 'jauk', 'jaup', 'java', 'jaws', 'jays',
    'jazz', 'jean', 'jeed', 'jeep', 'jeer', 'jees', 'jeez',
    'jefe', 'jehu', 'jell', 'jeon', 'jerk', 'jess', 'jest',
    'jete', 'jets', 'jeux', 'jiao', 'jibb', 'jibe', 'jibs',
    'jiff', 'jigs', 'jill', 'jilt', 'jimp', 'jink', 'jinn', 
    'jins', 'jinx', 'jird', 'jism', 'jive', 'jivy', 'jizz',
    'jobs', 'jock', 'joes', 'joey', 'jogs', 'john', 'join',
    'joke', 'joky', 'jole', 'jolt', 'jook', 'josh', 'joss', 
    'jota', 'jots', 'jouk', 'jowl', 'jows', 'joys', 'juba',
    'jube', 'juco', 'judo', 'judy', 'juga', 'jugs', 'juju',
    'juke', 'juku', 'jump', 'jupe', 'jura', 'jury', 'just',
    'jute', 'juts', 'koji', 'mojo', 'puja', 'raja', 'soja',
    'soju'
  ],
  'q' : [
    'qi',
    'qat', 'qis', 'qua', 'suq',
    'aqua', 'cinq', 'qadi', 'qaid', 'qats', 'qoph', 'quad', 
    'quag', 'quai', 'quay', 'quey', 'quid', 'quin', 'quip', 
    'quit', 'quiz', 'quod', 'suqs'
  ],
  'x' : [
    'ax', 'ex', 'ox', 'xi', 'xu', 
    'axe', 'box', 'cox', 'dex', 'fax', 'fix', 'fox', 'gox',
    'hex', 'kex', 'lax', 'lex', 'lox', 'lux', 'max', 'mix',
    'mux', 'nix', 'oxo', 'oxy', 'pax', 'pix', 'pox',
    'pyx', 'rax', 'rex', 'sax', 'sex', 'six', 'sox', 'tax',
    'tix', 'tux', 'vex', 'vox', 'wax', 'xed', 'xis', 'zax',
    'apex', 'axal', 'axed', 'axel', 'axes', 'axil', 'axis',
    'axle', 'axon', 'boxy', 'brux', 'calx', 'coax', 'coxa',
    'crux', 'dexy', 'doux', 'doxy', 'eaux', 'exam', 'exec',
    'exed', 'exes', 'exit', 'exon', 'expo', 'falx', 'faux',
    'fixt', 'flax', 'flex', 'flux', 'foxy', 'hoax', 'ibex',
    'ilex', 'ixia', 'jeux', 'jinx', 'luxe', 'lynx', 'maxi',
    'minx', 'mixt', 'moxa', 'next', 'nixe', 'nixy', 'onyx',
    'oryx', 'oxen', 'oxer', 'oxes', 'oxic', 'oxid', 'oxim',
    'pixy', 'plex', 'poxy', 'prex', 'roux', 'sext', 'taxa',
    'taxi', 'text', 'vext', 'waxy', 'xyst'
  ],
  'z' : [
    'za', 
    'adz', 'azo', 'biz', 'coz', 'cuz', 'fez', 'fiz', 'rez',
    'sez', 'tiz', 'wiz', 'wuz', 'yez', 'zag', 'zap', 'zas',
    'zax', 'zed', 'zee', 'zek', 'zen', 'zep', 'zig', 'zin',
    'zip', 'zit', 'zoa', 'zoo', 'zuz', 'zzz',
    'adze', 'azan', 'azon', 'bazz', 'bize', 'bozo', 'buzz',
    'cazh', 'chez', 'cozy', 'czar', 'daze', 'ditz', 'doze',
    'dozy', 'faze', 'fizz', 'fozy', 'friz', 'futz', 'fuze',
    'fuzz', 'gaze', 'geez', 'griz', 'haze', 'hazy', 'izar',
    'jazz', 'jeez', 'jizz', 'laze', 'lazy', 'lutz', 'maze',
    'mazy', 'meze', 'mozo', 'nazi', 'ooze', 'oozy', 'orzo',
    'ouzo', 'oyez', 'phiz', 'prez', 'putz', 'quiz', 'raze',
    'razz', 'ritz', 'size', 'sizy', 'tizz', 'tzar', 'whiz',
    'yutz', 'yuzu', 'zags', 'zany', 'zaps', 'zarf', 'zeal',
    'zebu', 'zeda', 'zeds', 'zees', 'zein', 'zeks', 'zeps',
    'zerk', 'zero', 'zest', 'zeta', 'zigs', 'zill', 'zinc',
    'zine', 'zing', 'zins', 'zips', 'ziti', 'zits', 'zizz', 
    'zoea', 'zoic', 'zona', 'zone', 'zonk', 'zoom', 'zoon',
    'zoos', 'zori', 'zouk', 'zyme'
  ]
};

export default shortJQXZs;
